import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import Header from './components/Header';
import Footer from './components/Footer';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>

      <body className="">
        <Header />

        <main className="bg-base-200 py-20 px-55 space-y-10">
          <Suspense fallback={<div className='mx-auto'><span className="loading loading-bars loading-xs"></span>
            <span className="loading loading-bars loading-sm"></span>
            <span className="loading loading-bars loading-md"></span>
          </div>}>
            {children}
          </Suspense>
        </main>

        <ToastContainer />

        <Footer />
      </body>
    </html>
  );
}